version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - FLASK_ENV=development
      - HF_TOKEN=your_huggingface_token
      - TZ=Asia/Ho_Chi_Minh